### ISSUE TITLE
login request fail - status code 403

### ISSUE THREAD

**Issue by olvier** [adevjoe/qbittorrent-notify#4]
Did not changed anything.

Port and ID:PW are the same.

qBittorrent v4.4.5 Web UI (64-bit)

any idea? Maybe it came with some qbit update?

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13106409/197034374-550a385c-ab5b-42fc-bd2f-5b602016a8ee.png">

**Comment by adevjoe** [comment]
My qBittorrent is v4.4.5, the program is work. Please try restart program. I think the api is not change in the qBittorrent patch version.

**Comment by olvier** [comment]
Weird. I restarted both container more than once.

**Comment by adevjoe** [comment]
qBittorrent change login api in version 4.4.4, fixed in #5.

**Comment by olvier** [comment]
Hm. Don't know what to do now :)

Updated to :latest but the error still exist.

Also changed ban to 5 seconds instead 3600, to become "connectable" again, but still the same behavior.

Any idea?

edit:
Maybe I was too fast with updating ;)
Now it works like CHARM... (again!) !!! Thank you so much!

<img width="408" alt="image" src="https://user-images.githubusercontent.com/13106409/197270270-883b8855-cbe1-4e21-a2f7-9e53df779eab.png">
